# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
#script:
#  - mvn test -B
#
jdk:
  - openjdk14

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)
# Start PostgreSQL
services:
  - postgresql
# Create a database
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

# Отправлять уведомление на почту youremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - saimon494@outlook.com
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
    - CODECOV_TOKEN="1857b31a-0cc7-46c3-b7b2-50049a626c59"