insert into role(name) values ('admin');
insert into role(name) values ('user');
select * from role;
insert into users(name, role_id) values ('Vasya', 1);
insert into users(name, role_id) values ('Vova', 2);
insert into users(name, role_id) values ('Goga', 2);
select * from users;
insert into rules(name) values ('read/write');
insert into rules(name) values ('read');
select * from rules;
insert into role_rules(role_id, rules_id) VALUES (1, 1);
insert into role_rules(role_id, rules_id) VALUES (2, 2);
select * from role_rules;
insert into category(name) values ('access');
insert into category(name) values ('install');
select * from category;
insert into state(name) values ('new');
insert into state(name) values ('in progress');
insert into state(name) values ('complete');
select * from state;
insert into item(name, user_id, category_id, state_id) VALUES ('task1', 2, 1, 1);
insert into item(name, user_id, category_id, state_id) VALUES ('task2', 3, 2, 2);
insert into item(name, user_id, category_id, state_id) VALUES ('task3', 1, 2, 3);
select * from item;
insert into comments(name, item_id) values ('comment1', 1);
insert into comments(name, item_id) values ('comment2', 2);
insert into comments(name, item_id) values ('comment3', 3);
select * from comments;
insert into attachs(name, item_id) values ('file', 1);
insert into attachs(name, item_id) values ('screenshot', 2);
insert into attachs(name, item_id) values ('error', 3);
select * from attachs;